#168369756 Refactor endpoints to use permission based authorisation
andela/coding-geeks-ah-backend pull request #50
Opened 2019-09-10 19:46 UTC by harerakalex

### What does this PR do?
- Refactor endpoints to use permission based authorisation
### Description of Task to be done?
- Create permissions
- Check permission in the routes
### How should this be manually tested?
- clone this branch
- run seeds
- Run `npm start`
- For example try to use this route `http://localhost:3000/api/v1/articles/slug/reports/id` of reading a single report with the token of a normal user
### Any background context you want to provide?
- N/A
### What are the relevant pivotal tracker stories?
- [Refactor endpoints to use permission based authorisation](https://www.pivotaltracker.com/story/show/168369756)
### Questions
- N/A
### Screenshots
<img width="1127" alt="Screen Shot 2019-09-10 at 21 19 53" src="https://user-images.githubusercontent.com/39116572/64643497-c7503b00-d410-11e9-9601-60bcf5a9c799.png">

2019-09-12 08:43 UTC, placideirandora requested changes
I'm able to retrieve a specific article's report. I think your PR is not descriptive enough for us to know how to test your feature. Please put many details for us to know what to do.
<img width="1132" alt="Screen Shot 2019-09-12 at 10 41 48" src="https://user-images.githubusercontent.com/34879554/64768693-32e9f380-d54a-11e9-972c-03efccb23115.png">

2019-09-12 09:02 UTC, malaba6 requested changes

2019-09-12 09:02 UTC, malaba6 commented on src/sequelize/seeders/20190910132709-user-permissions.js
> +  permission: 'create article',
I think you should follow the guideline as specified in this feature's description about naming permissions. So the permission `create article` should be named `CREATE_ARTICLE`. Here is the dev notes from the PT board
<img width="358" alt="Screen Shot 2019-09-12 at 10 56 58" src="https://user-images.githubusercontent.com/50101879/64770037-adb40e00-d54c-11e9-94ca-41e3c283fce6.png">

2019-09-12 09:33 UTC, harerakalex commented
> I'm able to retrieve a specific article's report. I think your PR is not descriptive enough for us to know how to test your feature. Please put many details for us to know what to do.
> <img alt="Screen Shot 2019-09-12 at 10 41 48" width="1132" src="https://user-images.githubusercontent.com/34879554/64768693-32e9f380-d54a-11e9-972c-03efccb23115.png">

@placideirandora try to use the normal user token in order to test this feature.

2019-09-12 09:36 UTC, Jkadhuwa reviewed
Looks okay.

2019-09-12 09:37 UTC, placideirandora commented
> > I'm able to retrieve a specific article's report. I think your PR is not descriptive enough for us to know how to test your feature. Please put many details for us to know what to do.
> > <img alt="Screen Shot 2019-09-12 at 10 41 48" width="1132" src="https://user-images.githubusercontent.com/34879554/64768693-32e9f380-d54a-11e9-972c-03efccb23115.png">
> 
> @placideirandora try to use the normal user token in order to test this feature.

I do know that even before a normal user could not retrieve a report. So, what's new?

2019-09-12 09:40 UTC, Jkadhuwa commented
> > @placideirandora try to use the normal user token in order to test this feature.
> 
> I do know that even before a normal user could not retrieve a report. So, what's new?

@placideirandora, are you saying you can retrieve a report when you are not an admin or a super-admin?

2019-09-12 09:41 UTC, placideirandora commented
> > > @placideirandora try to use the normal user token in order to test this feature.
> > 
> > 
> > I do know that even before a normal user could not retrieve a report. So, what's new?
> 
> @placideirandora, are you saying you can retrieve a report when you are not an admin or a super-admin?

Before, an admin could retrieve the report and now they still can. And a normal user couldn't and now, they couldn't. So, what's the change?

2019-09-12 09:42 UTC, harerakalex commented
> > > I'm able to retrieve a specific article's report. I think your PR is not descriptive enough for us to know how to test your feature. Please put many details for us to know what to do.
> > > <img alt="Screen Shot 2019-09-12 at 10 41 48" width="1132" src="https://user-images.githubusercontent.com/34879554/64768693-32e9f380-d54a-11e9-972c-03efccb23115.png">
> > 
> > 
> > @placideirandora try to use the normal user token in order to test this feature.
> 
> I do know that even before a normal user could not retrieve a report. So, what's new?

So what actually do you want?

2019-09-12 09:43 UTC, placideirandora commented
> > > > I'm able to retrieve a specific article's report. I think your PR is not descriptive enough for us to know how to test your feature. Please put many details for us to know what to do.
> > > > <img alt="Screen Shot 2019-09-12 at 10 41 48" width="1132" src="https://user-images.githubusercontent.com/34879554/64768693-32e9f380-d54a-11e9-972c-03efccb23115.png">
> > > 
> > > 
> > > @placideirandora try to use the normal user token in order to test this feature.
> > 
> > 
> > I do know that even before a normal user could not retrieve a report. So, what's new?
> 
> So what actually do you want?

I would expect an admin to be revoked access of retrieving a report by a super admin and check that works? And again, the super admin could grant back admin with access to retrieve the report and check if that works as well.

2019-09-12 09:46 UTC, Jkadhuwa commented
> Before, an admin could retrieve the report and now they still can. And a normal user couldn't and now, they couldn't. So, what's the change?

@placideirandora, The importance of this PR is just refactoring the permissions. And if you want to revoke permissions for a particular role then you should delete that permission from the specific role.

2019-09-12 09:50 UTC, placideirandora commented
> > Before, an admin could retrieve the report and now they still can. And a normal user couldn't and now, they couldn't. So, what's the change?
> 
> @placideirandora, The importance of this PR is just refactoring the permissions. And if you want to revoke permissions for a particular role then you should delete that permission from the specific role.

But we should be able to test the permission functionality? He should have included that in the README where the permission is granted and revoked with examples.

2019-09-12 12:58 UTC, harerakalex commented on src/sequelize/seeders/20190910132709-user-permissions.js
> +  permission: 'create article',
@Malaba6 , change you requested is done

2019-09-12 13:10 UTC, mkiterian commented on src/sequelize/seeders/20190910132709-user-permissions.js
> +  permission: 'CREATE_ARTICLE',
what was meant by this is that you define the permissions as string constants in a file e.g `permissionConstants.js` and then define permissions as `const CREATE_ARTICLE = 'create article'` . This way there's a single source of truth for the string value

2019-09-12 13:19 UTC, malaba6 approved these changes

2019-09-12 14:37 UTC, placideirandora requested changes

2019-09-12 14:37 UTC, placideirandora commented on src/controllers/permissionController.js
>      const newPermission = req.body.permission;
I think you should also check/validate if the permission to be created is valid because you already know them. I was able to create invalid permissions which I know that they cannot work. Therefore, you should validate permissions for us to avoid data redundancy in the database or unwanted information because of validation bypass.
<img width="1134" alt="Screen Shot 2019-09-12 at 16 37 08" src="https://user-images.githubusercontent.com/34879554/64793596-97717680-d57b-11e9-9b47-02ba95b77209.png">
<img width="1132" alt="Screen Shot 2019-09-12 at 16 40 02" src="https://user-images.githubusercontent.com/34879554/64793878-ffc05800-d57b-11e9-8b75-49960ef9fb1f.png">

2019-09-12 15:08 UTC, harerakalex commented on src/controllers/permissionController.js
>      const newPermission = req.body.permission;
Yes, that's true.

2019-09-12 15:20 UTC, harerakalex commented on src/controllers/permissionController.js
>      const newPermission = req.body.permission;
Done!

2019-09-12 15:32 UTC, placideirandora commented on src/controllers/permissionController.js
>      const newPermission = req.body.permission;
Great!

2019-09-12 15:32 UTC, placideirandora approved these changes

2019-09-12 15:34 UTC, placideirandora commented on src/controllers/permissionController.js
>      const newPermission = req.body.permission;
I have checked that you have implemented the feedback and approved the changes.

2019-09-12 15:34 UTC, harerakalex commented
> I would expect an admin to be revoked access of retrieving a report by a super admin and check that works? And again, the super admin could grant back admin with access to retrieve the report and check if that works as well.

Done check the above screenshot

2019-09-12 15:35 UTC, placideirandora commented
> > I would expect an admin to be revoked access of retrieving a report by a super admin and check that works? And again, the super admin could grant back admin with access to retrieve the report and check if that works as well.
> 
> Done check the above screenshot

I have checked that you have implemented the feedback and approved the changes.

2019-09-13 07:00 UTC, mkiterian approved these changes

2019-09-13 07:00 UTC, merged